"""Backtest the edge-finder against held-out test data using synthetic market odds."""
import logging
from typing import Any

import pandas as pd

logger = logging.getLogger(__name__)


def simulate_market_odds(
    home_market_prob: float = 0.5,
    vig: float = 0.0476,
) -> tuple[float, float]:
    """Generate synthetic American odds for both sides of a game.

    Splits the vig additively across home and away implied probabilities,
    then converts each to American odds format.

    At the default home_market_prob=0.5, vig=0.0476, both sides return
    approximately -110.0 (the standard even-money MLB line).

    Args:
        home_market_prob: Market-implied probability that home wins. Default 0.5.
        vig: Bookmaker overround (sum of implied probs minus 1). Default 0.0476.

    Returns:
        (home_american, away_american) as floats.
    """
    home_implied = home_market_prob + vig / 2
    away_implied = (1.0 - home_market_prob) + vig / 2

    def _to_american(p: float) -> float:
        if p >= 0.5:
            return -(p / (1.0 - p)) * 100.0
        return ((1.0 - p) / p) * 100.0

    return _to_american(home_implied), _to_american(away_implied)


def run_backtest(
    clf: Any,
    training_df: pd.DataFrame,
    home_market_prob: float = 0.5,
    vig: float = 0.0476,
    unit: float = 100.0,
) -> pd.DataFrame:
    """Simulate edge-finder performance on the held-out 20% test split.

    Replicates the same 80/20 stratified split used in model._three_way_split()
    (test_size=0.2, random_state=42) so the evaluated games are identical to
    those used in model.evaluate(). No data leakage.

    Synthetic market odds are generated by simulate_market_odds(home_market_prob, vig).
    The default -110/-110 market assumes 50/50 game pricing — the backtest measures
    whether the model outperforms a naive even-money assumption.

    Args:
        clf: Fitted calibrated classifier from model.load_model(). Must have
            feature_names_in_ and predict_proba() attributes.
        training_df: Full training DataFrame from training_data.load_training_set().
            Must contain home_win, game_date, home_name, away_name, and all feature
            columns referenced by clf.feature_names_in_.
        home_market_prob: Market-implied home win probability. Default 0.5.
        vig: Bookmaker overround. Default 0.0476 (approx -110/-110 standard line).
        unit: Dollar bet size for P&L calculation. Default $100.

    Returns:
        DataFrame sorted by game_date with columns: game_date, home_name, away_name,
        bet_side, american_odds, model_prob, ev, kelly_fraction, actual_home_win,
        won, pnl, cumulative_pnl. Returns empty DataFrame (with those columns) if
        no bets clear the EV threshold.
    """
    from sklearn.model_selection import train_test_split

    from mlb_edge_finder.config import EV_THRESHOLD, MIN_AMERICAN_ODDS
    from mlb_edge_finder.edge_finder import compute_ev, compute_kelly
    from mlb_edge_finder.model import NON_FEATURE_COLS, TARGET_COL

    output_cols = [
        "game_date", "home_name", "away_name", "bet_side",
        "american_odds", "model_prob", "ev", "kelly_fraction",
        "actual_home_win", "won", "pnl", "cumulative_pnl",
    ]

    non_feature = [c for c in NON_FEATURE_COLS if c in training_df.columns]
    X = training_df.drop(columns=non_feature)
    y = training_df[TARGET_COL]

    _, X_test, _, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    feature_names = list(clf.feature_names_in_)
    X_test_aligned = X_test.reindex(columns=feature_names)

    home_probs = clf.predict_proba(X_test_aligned)[:, 1]

    home_odds, away_odds = simulate_market_odds(home_market_prob, vig)
    home_payout = home_odds / 100 if home_odds > 0 else 100 / abs(home_odds)
    away_payout = away_odds / 100 if away_odds > 0 else 100 / abs(away_odds)

    meta = training_df.loc[X_test.index, ["game_date", "home_name", "away_name"]]

    records = []
    for (idx, prob), actual in zip(zip(X_test.index, home_probs), y_test.values):
        row_meta = meta.loc[idx]

        home_ev = compute_ev(float(prob), round(home_odds))
        if home_ev > EV_THRESHOLD and home_odds >= MIN_AMERICAN_ODDS:
            won = int(actual) == 1
            records.append({
                "game_date": row_meta["game_date"],
                "home_name": row_meta["home_name"],
                "away_name": row_meta["away_name"],
                "bet_side": "home",
                "american_odds": round(home_odds),
                "model_prob": round(float(prob), 4),
                "ev": round(home_ev, 4),
                "kelly_fraction": round(compute_kelly(float(prob), round(home_odds)), 4),
                "actual_home_win": int(actual),
                "won": won,
                "pnl": home_payout * unit if won else -unit,
            })

        away_prob = 1.0 - float(prob)
        away_ev = compute_ev(away_prob, round(away_odds))
        if away_ev > EV_THRESHOLD and away_odds >= MIN_AMERICAN_ODDS:
            won = int(actual) == 0
            records.append({
                "game_date": row_meta["game_date"],
                "home_name": row_meta["home_name"],
                "away_name": row_meta["away_name"],
                "bet_side": "away",
                "american_odds": round(away_odds),
                "model_prob": round(away_prob, 4),
                "ev": round(away_ev, 4),
                "kelly_fraction": round(compute_kelly(away_prob, round(away_odds)), 4),
                "actual_home_win": int(actual),
                "won": won,
                "pnl": away_payout * unit if won else -unit,
            })

    if not records:
        logger.warning("No edges found in backtest — model may not outperform even-money market")
        return pd.DataFrame(columns=output_cols)

    result = pd.DataFrame(records).sort_values("game_date").reset_index(drop=True)
    result["cumulative_pnl"] = result["pnl"].cumsum()
    logger.info("Backtest complete: %d bets placed across %d test games", len(result), len(X_test))
    return result
