"""Backtest the edge-finder against held-out test data using synthetic market odds."""
import json
import logging
from pathlib import Path
from typing import Any

import pandas as pd

logger = logging.getLogger(__name__)


def simulate_market_odds(
    home_market_prob: float = 0.5,
    vig: float = 0.0476,
) -> tuple[float, float]:
    """Generate synthetic American odds for both sides of a game.

    Splits the vig additively across home and away implied probabilities,
    then converts each to American odds format.

    At the default home_market_prob=0.5, vig=0.0476, both sides return
    approximately -110.0 (the standard even-money MLB line).

    Args:
        home_market_prob: Market-implied probability that home wins. Default 0.5.
        vig: Bookmaker overround (sum of implied probs minus 1). Default 0.0476.

    Returns:
        (home_american, away_american) as floats.
    """
    home_implied = home_market_prob + vig / 2
    away_implied = (1.0 - home_market_prob) + vig / 2

    def _to_american(p: float) -> float:
        if p >= 0.5:
            return -(p / (1.0 - p)) * 100.0
        return ((1.0 - p) / p) * 100.0

    return _to_american(home_implied), _to_american(away_implied)


def run_backtest(
    clf: Any,
    training_df: pd.DataFrame,
    home_market_prob: float = 0.5,
    vig: float = 0.0476,
    unit: float = 100.0,
    ev_threshold: float | None = None,
    min_prob_edge: float | None = None,
) -> pd.DataFrame:
    """Simulate edge-finder performance on the held-out 20% test split.

    Replicates the same 80/20 stratified split used in model._three_way_split()
    (test_size=0.2, random_state=42) so the evaluated games are identical to
    those used in model.evaluate(). No data leakage.

    Synthetic market odds are generated by simulate_market_odds(home_market_prob, vig).
    The default -110/-110 market assumes 50/50 game pricing.

    Args:
        clf: Fitted calibrated classifier from model.load_model(). Must have
            feature_names_in_ and predict_proba() attributes.
        training_df: Full training DataFrame from training_data.load_training_set().
            Must contain home_win, game_date, home_name, away_name, and all feature
            columns referenced by clf.feature_names_in_.
        home_market_prob: Market-implied home win probability. Default 0.5.
        vig: Bookmaker overround. Default 0.0476 (approx -110/-110 standard line).
        unit: Dollar bet size for P&L calculation. Default $100.
        ev_threshold: Minimum EV to flag a bet. Defaults to config.EV_THRESHOLD.
        min_prob_edge: Minimum gap between model_prob and market_implied_prob.
            Defaults to config.MIN_PROB_EDGE.

    Returns:
        DataFrame sorted by game_date with columns: game_date, home_name, away_name,
        bet_side, american_odds, model_prob, ev, kelly_fraction, actual_home_win,
        won, pnl, cumulative_pnl. Returns empty DataFrame (with those columns) if
        no bets clear the thresholds.
    """
    from sklearn.model_selection import train_test_split

    from mlb_edge_finder import config as _config
    from mlb_edge_finder.edge_finder import compute_ev, compute_kelly, market_implied_prob
    from mlb_edge_finder.model import NON_FEATURE_COLS, TARGET_COL

    _ev_threshold = ev_threshold if ev_threshold is not None else _config.EV_THRESHOLD
    _min_prob_edge = min_prob_edge if min_prob_edge is not None else _config.MIN_PROB_EDGE

    output_cols = [
        "game_date", "home_name", "away_name", "bet_side",
        "american_odds", "model_prob", "ev", "kelly_fraction",
        "actual_home_win", "won", "pnl", "cumulative_pnl",
    ]

    non_feature = [c for c in NON_FEATURE_COLS if c in training_df.columns]
    X = training_df.drop(columns=non_feature)
    y = training_df[TARGET_COL]

    _, X_test, _, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    feature_names = list(clf.feature_names_in_)
    X_test_aligned = X_test.reindex(columns=feature_names)

    home_probs = clf.predict_proba(X_test_aligned)[:, 1]

    home_odds_f, away_odds_f = simulate_market_odds(home_market_prob, vig)
    home_odds_i = round(home_odds_f)
    away_odds_i = round(away_odds_f)
    home_payout = home_odds_i / 100 if home_odds_i > 0 else 100 / abs(home_odds_i)
    away_payout = away_odds_i / 100 if away_odds_i > 0 else 100 / abs(away_odds_i)

    home_market_implied = market_implied_prob(home_odds_i)
    away_market_implied = market_implied_prob(away_odds_i)

    meta = training_df.loc[X_test.index, ["game_date", "home_name", "away_name"]]

    records = []
    for (idx, prob), actual in zip(zip(X_test.index, home_probs), y_test.values):
        row_meta = meta.loc[idx]

        home_ev = compute_ev(float(prob), home_odds_i)
        home_edge = float(prob) - home_market_implied
        if (home_ev > _ev_threshold
                and home_odds_i >= _config.MIN_AMERICAN_ODDS
                and home_edge > _min_prob_edge):
            won = int(actual) == 1
            records.append({
                "game_date": row_meta["game_date"],
                "home_name": row_meta["home_name"],
                "away_name": row_meta["away_name"],
                "bet_side": "home",
                "american_odds": home_odds_i,
                "model_prob": round(float(prob), 4),
                "ev": round(home_ev, 4),
                "kelly_fraction": round(compute_kelly(float(prob), home_odds_i), 4),
                "actual_home_win": int(actual),
                "won": won,
                "pnl": home_payout * unit if won else -unit,
            })

        away_prob = 1.0 - float(prob)
        away_ev = compute_ev(away_prob, away_odds_i)
        away_edge = away_prob - away_market_implied
        if (away_ev > _ev_threshold
                and away_odds_i >= _config.MIN_AMERICAN_ODDS
                and away_edge > _min_prob_edge):
            won = int(actual) == 0
            records.append({
                "game_date": row_meta["game_date"],
                "home_name": row_meta["home_name"],
                "away_name": row_meta["away_name"],
                "bet_side": "away",
                "american_odds": away_odds_i,
                "model_prob": round(away_prob, 4),
                "ev": round(away_ev, 4),
                "kelly_fraction": round(compute_kelly(away_prob, away_odds_i), 4),
                "actual_home_win": int(actual),
                "won": won,
                "pnl": away_payout * unit if won else -unit,
            })

    if not records:
        logger.warning("No edges found in backtest at EV=%.0f%% edge=%.0f%%",
                       _ev_threshold * 100, _min_prob_edge * 100)
        return pd.DataFrame(columns=output_cols)

    result = pd.DataFrame(records).sort_values("game_date").reset_index(drop=True)
    result["cumulative_pnl"] = result["pnl"].cumsum()
    logger.info(
        "Backtest complete: %d bets across %d test games (EV=%.0f%% edge=%.0f%%)",
        len(result), len(X_test), _ev_threshold * 100, _min_prob_edge * 100,
    )
    return result


def compute_summary(backtest_df: pd.DataFrame, unit: float = 100.0) -> dict:
    """Compute headline performance metrics for a completed backtest.

    Args:
        backtest_df: Output of run_backtest(). Must have columns pnl,
            cumulative_pnl, won, ev. Accepts empty DataFrames (all metrics = 0).
        unit: Dollar bet size used in run_backtest(). Used to compute ROI.

    Returns:
        Dict with keys:
            n_bets       — total number of bets placed
            n_wins       — number of winning bets
            win_rate     — n_wins / n_bets (0.0 if no bets)
            total_pnl    — sum of all bet P&Ls
            roi_pct      — total_pnl / (n_bets * unit) * 100
            avg_ev       — mean expected value of flagged bets
            max_drawdown — largest peak-to-trough drop in cumulative P&L
            sharpe_ratio — per-bet Sharpe: mean(pnl) / std(pnl), or 0.0 if std=0
    """
    if backtest_df.empty:
        return {
            "n_bets": 0,
            "n_wins": 0,
            "win_rate": 0.0,
            "total_pnl": 0.0,
            "roi_pct": 0.0,
            "avg_ev": 0.0,
            "max_drawdown": 0.0,
            "sharpe_ratio": 0.0,
        }

    n_bets = len(backtest_df)
    n_wins = int(backtest_df["won"].sum())
    total_pnl = float(backtest_df["pnl"].sum())

    cumulative = backtest_df["cumulative_pnl"]
    running_max = cumulative.cummax()
    max_drawdown = float((running_max - cumulative).max())

    pnl_std = backtest_df["pnl"].std()
    sharpe = float(backtest_df["pnl"].mean() / pnl_std) if pnl_std > 0 else 0.0

    return {
        "n_bets": n_bets,
        "n_wins": n_wins,
        "win_rate": round(n_wins / n_bets, 4),
        "total_pnl": round(total_pnl, 2),
        "roi_pct": round(total_pnl / (n_bets * unit) * 100, 2),
        "avg_ev": round(float(backtest_df["ev"].mean()), 4),
        "max_drawdown": round(max_drawdown, 2),
        "sharpe_ratio": round(sharpe, 4),
    }


def sweep_thresholds(
    clf: Any,
    training_df: pd.DataFrame,
    ev_low: float = 0.05,
    ev_high: float = 0.50,
    ev_step: float = 0.05,
    prob_edge_low: float = 0.00,
    prob_edge_high: float = 0.30,
    prob_edge_step: float = 0.05,
    unit: float = 100.0,
) -> pd.DataFrame:
    """Sweep (ev_threshold, min_prob_edge) combinations and rank by Sharpe ratio.

    Runs run_backtest() at each combination using the synthetic -110/-110 market.
    Combinations that produce 0 bets are excluded from results.

    Args:
        clf: Fitted calibrated classifier.
        training_df: Full training DataFrame from training_data.load_training_set().
        ev_low: Minimum EV threshold to sweep (inclusive). Default 0.05.
        ev_high: Maximum EV threshold to sweep (inclusive). Default 0.50.
        ev_step: Step size for EV threshold sweep. Default 0.05.
        prob_edge_low: Minimum prob-edge to sweep (inclusive). Default 0.00.
        prob_edge_high: Maximum prob-edge to sweep (inclusive). Default 0.30.
        prob_edge_step: Step size for prob-edge sweep. Default 0.05.
        unit: Dollar bet size passed to run_backtest(). Default $100.

    Returns:
        DataFrame sorted by sharpe_ratio descending with columns:
        ev_threshold, min_prob_edge, n_bets, win_rate, roi_pct,
        sharpe_ratio, avg_bets_per_day.

    Raises:
        RuntimeError: If every combination produces 0 bets (model is broken).
    """
    import numpy as np

    n_ev = round((ev_high - ev_low) / ev_step) + 1
    n_edge = round((prob_edge_high - prob_edge_low) / prob_edge_step) + 1
    ev_values = [round(ev_low + i * ev_step, 4) for i in range(n_ev)]
    edge_values = [round(prob_edge_low + i * prob_edge_step, 4) for i in range(n_edge)]

    total = len(ev_values) * len(edge_values)
    logger.info("Starting threshold sweep: %d combinations", total)

    rows = []
    for i, (ev_t, edge_t) in enumerate(
        (ev, edge) for ev in ev_values for edge in edge_values
    ):
        if i > 0 and i % 10 == 0:
            logger.info("Threshold sweep: %d/%d complete", i, total)

        bt = run_backtest(clf, training_df, ev_threshold=ev_t,
                          min_prob_edge=edge_t, unit=unit)
        if bt.empty:
            logger.debug(
                "Skipping EV=%.0f%% edge=%.0f%% — no bets at this threshold",
                ev_t * 100, edge_t * 100,
            )
            continue

        summary = compute_summary(bt, unit=unit)
        if summary["n_bets"] == 0:
            continue

        avg_bets_per_day = (
            summary["n_bets"] / bt["game_date"].nunique()
            if bt["game_date"].nunique() > 0 else 0.0
        )
        rows.append({
            "ev_threshold": ev_t,
            "min_prob_edge": edge_t,
            "n_bets": summary["n_bets"],
            "win_rate": summary["win_rate"],
            "roi_pct": summary["roi_pct"],
            "sharpe_ratio": summary["sharpe_ratio"],
            "avg_bets_per_day": round(avg_bets_per_day, 2),
        })

    if not rows:
        raise RuntimeError("Threshold sweep produced no valid combinations — model may be broken")

    result = pd.DataFrame(rows).sort_values("sharpe_ratio", ascending=False).reset_index(drop=True)

    best = result.iloc[0]
    logger.info(
        "Optimal: EV=%.0f%% MIN_PROB_EDGE=%.0f%% Sharpe=%.3f (%d bets, %.1f/day)",
        best["ev_threshold"] * 100,
        best["min_prob_edge"] * 100,
        best["sharpe_ratio"],
        best["n_bets"],
        best["avg_bets_per_day"],
    )
    return result


def export_pnl_json(backtest_df: pd.DataFrame, summary: dict, path: Path) -> None:
    """Export cumulative P&L curve and summary stats to a JSON file.

    Args:
        backtest_df: Output of run_backtest(). Must have cumulative_pnl column.
        summary: Output of compute_summary().
        path: Destination path for the JSON file. Parent dirs created if needed.
    """
    data = {
        "cumulative_pnl": [round(v, 2) for v in backtest_df["cumulative_pnl"].tolist()],
        "summary": summary,
    }
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(json.dumps(data, indent=2))
    logger.info("Exported P&L JSON to %s (%d bets)", path, len(backtest_df))
